# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('plugins', '0002_contact_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomContact',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_customcontact', serialize=False, to='cms.CMSPlugin')),
                ('form_name', models.CharField(blank=True, help_text='Used to distinguish multiple contact forms on the same site.', max_length=60, verbose_name='Form name')),
                ('form_layout', models.CharField(choices=[(b'cmsplugin_contact.forms.ContactForm', 'default')], help_text='Choice the layout of contact form', max_length=255, verbose_name='Form Layout')),
                ('site_email', models.EmailField(max_length=254, verbose_name='Email recipient')),
                ('thanks', models.TextField(default='Thank you for your message.', help_text='Message displayed on successful submit', max_length=200, verbose_name='Thanks message')),
                ('submit', models.CharField(default='Submit', max_length=30, verbose_name='Submit button value')),
                ('spam_protection_method', models.SmallIntegerField(choices=[(0, b'Honeypot'), (1, b'Akismet'), (2, b'ReCAPTCHA')], default=0, verbose_name='Spam protection method')),
                ('akismet_api_key', models.CharField(blank=True, max_length=255)),
                ('recaptcha_public_key', models.CharField(blank=True, max_length=255)),
                ('recaptcha_private_key', models.CharField(blank=True, max_length=255)),
                ('recaptcha_theme', models.CharField(choices=[(b'clean', b'Clean'), (b'red', b'Red'), (b'white', b'White'), (b'blackglass', b'Black Glass'), (b'custom', b'Custom')], default=b'clean', max_length=20, verbose_name='ReCAPTCHA theme')),
                ('redirect_url', models.URLField(blank=True, help_text='If it is set, the form redirect to url when the form is valid', verbose_name='URL Redirection')),
                ('custom_label', models.CharField(default='Your custom value', max_length=20, verbose_name='Custom sender label')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_contact', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_slider', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
